import Header from '@/components/Header'
import Footer from '@/components/Footer'
import type { Metadata } from 'next'
import ThemeContextProvider from '@/context/theme'
import { CssBaseline } from '@mui/material'

//font import 
import '@fontsource/inter'; // Make sure the import path is correct

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@300;400;500;700&display=swap"/>
      </head>
      <body>
        <ThemeContextProvider>
          <CssBaseline />
          <Header />
          {children}
          <Footer />
        </ThemeContextProvider>
      </body>
    </html>
  )
}
